### ISSUE TITLE
Shortened URL copy as QR Code

### ISSUE THREAD

**Issue by aigdonia** [origranot/url-shortener#102]
As A Shortened URL creator, I need to copy the shortened URL as a QR Code

this should be useful for sharing the URL in printable scannable formats, it saves additonal step of using another service to generate QR code.

## Acceptance Criteria
- After creating a shortened URL, display button suggests if need to get QR format copy
- button should be clickable and after click on it, it should generate a QR version of shortened url and displays it
- QR image should be copied to clipboard and notify user about successful copy in clipboard.
- QR image should not be stored on server in order not to consume space.

**Comment by origranot** [comment]
Amazing idea, go for it!!

**Comment by origranot** [comment]
?Are you still working on it

**Comment by ArnabDey1543** [comment]
@origranot can you please assign this work ?

**Comment by IncredibleZuess** [comment]
@origranot I'll work on this issue! :)
