### ISSUE TITLE
Clear input field after shortening url

### ISSUE THREAD

**Issue by BWsix** [origranot/url-shortener#105]
HI, I'm thinking that maybe clearing input field after shortening url world create a better user experience for those who have more than one url to shorten?
Currently, users have to delete their input if they want to shorten another link (like the screenshot below).

![image](https://user-images.githubusercontent.com/57709309/194697985-64c94c7a-a90c-4b7a-a359-5f3f5602d68f.png)

Does this sound like a good idea to you? if so, I'm willing to make this small change.

**Comment by Gauravdarkslayer** [comment]
Hey @BWsix and @origranot , I am working on this issue. Can you please assign it to me ?
Thank you !!

**Comment by BWsix** [comment]
This issue is fixed in #106
