### ISSUE TITLE
Multistage build in Dockerfile

### ISSUE THREAD

**Issue by detronetdip** [origranot/url-shortener#116]
https://github.com/origranot/url-shortener/blob/dd5979e840b851371aa8d886f7b34c6c38f35455/Dockerfile#L21

Hey @origranot wouldn't it be great if we use multistage build and build our application? Currently to build the docker image we are just copying the files and running the app in development without building it. I can implement that, please let me know your view to this and if you agree please assign me.

**Comment by origranot** [comment]
Yea, we can do a build stage.

Go for it!
