### ISSUE TITLE
Write a documentation about URL Shortner

### ISSUE THREAD

**Issue by utkarsh006** [origranot/url-shortener#135]
- Write an article about how the URL Shortner works in the background.
- This article would be on Low Level System Design.
- Do consider this issue under hacktoberfest.

**Comment by origranot** [comment]
Go for it. 👍

**Comment by utkarsh006** [comment]
@origranot Kindly give this issue a label as "hacktoberfest"

**Comment by origranot** [comment]
Yes, I will label the PR 👍
