### ISSUE TITLE
Update project gif

### ISSUE THREAD

**Issue by origranot** [origranot/url-shortener#144]
We need to update the project gif with the new UI changes.

**Comment by owengaspard** [comment]
On it

**Comment by ArnabDey1543** [comment]
@origranot  please assign me this work

**Comment by GuillemPM** [comment]
> @origranot please assign me this work

@ArnabDey1543, this issue has a PR #145 already.

Would you work on any of the remaining open issues?
Thanks! 🚀

**Comment by ArnabDey1543** [comment]
> > @origranot please assign me this work
> 
> @ArnabDey1543, this issue has a PR #145 already.
> 
> Would you work on any of the remaining open issues? Thanks! 🚀

sure !
