### ISSUE TITLE
Issue: Overlapping QR and Waves

### ISSUE THREAD

**Issue by GuillemPM** [origranot/url-shortener#160]
## Description
When I use the shortener on my phone and I generate the QR Code, the text to download it is overlapped by the waves, so it's not clickable, and difficult to read.

## Screenshot
![image](https://user-images.githubusercontent.com/26607131/195048953-65c7df05-9fa6-4094-b3ff-857f6fb716b4.png)

Mobile:
iPhone 11 (iOS 15.6.1)

Browser:
Safari 15

**Comment by origranot** [comment]
Done by https://github.com/origranot/url-shortener/pull/199
