### ISSUE TITLE
Spelling Mistake on the landing page

### ISSUE THREAD

**Issue by devilkiller-ag** [origranot/url-shortener#162]
There is a spelling mistake on the landing page. Can I rectify it?
![Screenshot (25)](https://user-images.githubusercontent.com/43639341/195052093-9b318fe8-5e64-4b37-8d23-16b300dd18bb.png)

**Comment by origranot** [comment]
@devilkiller-ag 👋 

I didn't notice that, 🤣 

You are welcome to open a PR about it.
