### ISSUE TITLE
Shortener don't work as expected when router has a hashmark

### ISSUE THREAD

**Issue by GuillemPM** [origranot/url-shortener#176]
### Description

When the app URL contains a hashmark it is being included in the shortened URL, but it should be ignored.
Example:
https://url-shortener-live.herokuapp.com/#sometext

Url to short: http://randomurl.com

Result: https://url-shortener-live.herokuapp.com/#sometextun7fo

### Screenshots

![image](https://user-images.githubusercontent.com/26607131/195328179-0da05dfe-07d7-4d5a-a232-88a7e1a0b53d.png)

**Comment by akshat-rawat** [comment]
can I work on this issue?

**Comment by GuillemPM** [comment]
Sure! Thanks.
Be aware of PR #177 as it has important changes that will be merged soon.

**Comment by akshat-rawat** [comment]
Sure will keep in mind!
