### ISSUE TITLE
The url should not be cleared once shorten url button is clicked

### ISSUE THREAD

**Issue by Vikki123** [origranot/url-shortener#178]
### Description

As on today, the user entered url gets cleared when the user clicks on shorten url and the screen looks something like below

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/8450434/195384223-7947b1f7-9312-4578-8135-3caa7e0e6ada.png">

If we actually see, the user is out of context. The input field is blank and there is a shortned url.

Expected behavior
The url should not be cleared so that the user is in more context.

**Comment by GuillemPM** [comment]
Closing as it is working as intended.
