### ISSUE TITLE
BUG: The input bar is not responsive from mobile

### ISSUE THREAD

**Issue by origranot** [origranot/url-shortener#181]
### Description

Hey, 

The input bar seems to be out of border when using a mobile.
Pay attention we a major update to our fronted 💯 

### Screenshots

![image](https://user-images.githubusercontent.com/48911144/195435776-e5e9bbf4-f47a-4835-b28e-f3b4d3ec5d41.png)

**Comment by Yashpsct010** [comment]
Assign this issue to me

**Comment by origranot** [comment]
> Assign this issue to me

@Yashpsct010 Hey!

It's already fixed by PR https://github.com/origranot/url-shortener/pull/199
