### ISSUE TITLE
Migrating app to a backend framework.

### ISSUE THREAD

**Issue by ashutoshshisodia** [origranot/url-shortener#23]
It would be great if we can move it to an MVC framework for backend.
AdonisJs  ( https://github.com/adonisjs/core ) is a great one.
Let me know your thoughts @origranot

**Comment by origranot** [comment]
@ashutoshshisodia Thank you for the suggestion!

The framework I thought about is NestJS (https://github.com/nestjs/nest)
We can use a lot of NestJS core features (logging, cache and more).

Do you want to open a PR while migrating it?

**Comment by ashutoshshisodia** [comment]
I have none experience in nest, let me see it once and I will get back to you.

**Comment by ashutoshshisodia** [comment]
Hi @origranot, can you once see AdonisJs (https://github.com/adonisjs/core) and let me know your views (not saying you must use it or anything)? 
It is quite feature rich fameword and I have been using it since a couple of years and I found it really good.
