### ISSUE TITLE
Add live link

### ISSUE THREAD

**Issue by Dun-sin** [origranot/url-shortener#24]
Add a live link of the project to the readme or about page

**Comment by origranot** [comment]
@Dun-sin @Savio629 

I will add a live link very soon.

**Comment by origranot** [comment]
@Dun-sin @Savio629 

Here is the link: https://url-shortener-live.herokuapp.com/
Do you want to add it to readme and add a pr?

**Comment by Dun-sin** [comment]
> @Dun-sin @Savio629 
> 
> Here is the link: https://url-shortener-live.herokuapp.com/
> Do you want to add it to readme and add a pr?

I can leave it up for some else to take

**Comment by drrav31** [comment]
@origranot Can I take this up and add the link in readme?

**Comment by VaishantMakan** [comment]
@origranot 

> @Dun-sin @Savio629
> 
> Here is the link: https://url-shortener-live.herokuapp.com/ Do you want to add it to readme and add a pr?

Can I take this up? I will add the live link in the readme and create a pull request.
