### ISSUE TITLE
Bug: Link copied message for invalid url as well

### ISSUE THREAD

**Issue by SameepAher** [origranot/url-shortener#41]
On clicking the display message of invalid link it says "Link has been copied to the clipboard" which doesn't make any sense

Here is the video displaying the issue - 

[screen-capture (1).webm](https://user-images.githubusercontent.com/96468766/194301649-12e0bc46-7fb6-4a4f-a765-886e93eff43a.webm)

I can fix this issue and create a PR

**Comment by origranot** [comment]
Correct, Go for it! 💯
