### ISSUE TITLE
Check for Invalid Url

### ISSUE THREAD

**Issue by Amiyanshu-web** [origranot/url-shortener#42]
Currently, the app is shortening the URL provided by the user irrespective of being valid or invalid.
The URL should be verified before shortening it.
If URL does not exist "Invalid URL" message should be shown.

**Comment by origranot** [comment]
Correct, you are more than welcome to create a PR about it.

**Comment by Ayush-Kori** [comment]
Hey I want to work on this issue and new to opensource can u guide me for this.

**Comment by origranot** [comment]
> Hey I want to work on this issue and new to opensource can u guide me for this.

You can checkout our Contribute.md file here: https://github.com/origranot/url-shortener/blob/master/CONTRIBUTE.MD
If you need further help let me know :)

**Comment by SandeshGC** [comment]
Currently, if you enter valid URL when the page is loaded, it works fine until it encounters an invalid URL. Once it encounters an invalid URL, it will display "The URL is invalid" although you enter a valid URL.

1.  On first load of page when the URL is valid:
 
![image](https://user-images.githubusercontent.com/59115123/194395074-ec441b89-ab6f-47ea-a6e8-fe61dfe7d5c9.png)

2. It will show valid URL if you continuously enter a valid URL (for now).
3. When it encounters an invalid URL

![image](https://user-images.githubusercontent.com/59115123/194395577-662a2160-678e-460b-b719-86c59510771a.png)

4. Now even though you enter any valid URL, it will be considered invalid (unless you reload the page).

![image](https://user-images.githubusercontent.com/59115123/194395727-091b0ffb-a478-4012-a052-528ba146e64d.png)

**Comment by Amiyanshu-web** [comment]
Hey @origranot after I pulled the latest release, every entered URL is getting an "invalid URL " error. Can you please once go through the latest merge which caused this issue?

**Comment by origranot** [comment]
Hey @Amiyanshu-web.

Can you check it again? for me it looks fine.

**Comment by origranot** [comment]
> Hey @origranot after I pulled the latest release, every entered URL is getting an "invalid URL " error. Can you please once go through the latest merge which caused this issue?

It is fixed. Do you want to work on a PR for this problem?

**Comment by Amiyanshu-web** [comment]
> > Hey @origranot after I pulled the latest release, every entered URL is getting an "invalid URL " error. Can you please once go through the latest merge which caused this issue?
> 
> It is fixed. Do you want to work on a PR for this problem?

Yes, I will create PR by today itself.

**Comment by origranot** [comment]
@Amiyanshu-web Great!
