### ISSUE TITLE
Button at the side of shorten url to use as it directly or part of the url

### ISSUE THREAD

**Issue by rachitag112** [origranot/url-shortener#46]
I would like to work on this issue!

**Comment by rachitag112** [comment]
Button to the side of the shorten url, you can either copy the link through clicking the button or can select the part of the link if wanted. As of now, if we click on the link it copies, but then you can also select the part of it or the whole link by the button.

**Comment by origranot** [comment]
@rachitag112 You can open a PR about it.
Not a problem.

**Comment by SandeshGC** [comment]
@rachitag112  
There should be a "Shorten URL" button which will shorten the URL and directly copy it to clipboard. Is that what you mean?

**Comment by rachitag112** [comment]
@SandeshGC 
That thing is already happening, you can refer to the screenshot to understand which kind of button I want to convey
![image](https://user-images.githubusercontent.com/76098066/194390150-24a3dfab-96a4-40d5-ad92-120c90800cac.png)
