### ISSUE TITLE
Shortened URL directing to https://https:// link

### ISSUE THREAD

**Issue by shunphoenix55** [origranot/url-shortener#48]
When you paste the link and it's shortened, the page it redirects to has https:// in it twice

**Steps to reproduce:**
1. Type in a link and press "Shorten URL"
2. Copy URL and paste in browser

**Screenshots**
![image](https://user-images.githubusercontent.com/76583147/194312889-a0040ed4-7b11-49e1-9521-4cbd994075ad.png)
![image](https://user-images.githubusercontent.com/76583147/194312961-0676808c-5e89-465b-902f-c7d7fedc51be.png)

**Comment by Bbhuva** [comment]
This issue is fixed and pull request is made

**Comment by origranot** [comment]
Correct. I fixed it and return the issue.
