### ISSUE TITLE
Missing docker file 

### ISSUE THREAD

**Issue by aliabbasjaffri** [origranot/url-shortener#50]
Hello! I saw that there's a docker file that's missing. Its better to have a docker of your application so that its easy to setup on any environment with just docker installed.
I can work on that, as a part of hacktoberfest and contribute towards url-shortner :-)

**Comment by origranot** [comment]
Sure, go for it :)

**Comment by aliabbasjaffri** [comment]
Hello @origranot , I've opened the [pull request](https://github.com/origranot/url-shortener/pull/63) for the issue.

**Comment by origranot** [comment]
Hey @aliabbasjaffri 

I commented on the pr.
