### ISSUE TITLE
Add copied animation 

### ISSUE THREAD

**Issue by sarthakk24** [origranot/url-shortener#58]
I would like to add a popup animation when the link is copied , also please assign me this issue if you want me to work on it

**Comment by origranot** [comment]
How about adding our git repo as a button at the top right?

**Comment by sarthakk24** [comment]
sure i'll can work on that

**Comment by origranot** [comment]
great!

**Comment by origranot** [comment]
@sarthakk24 any update?

**Comment by sarthakk24** [comment]
I am working on it actually I haven't worked with pug before so using pug docs to learn and apply

**Comment by origranot** [comment]
Alright, sounds great!
