### ISSUE TITLE
DOCS: Need to update readme 

### ISSUE THREAD

**Issue by origranot** [origranot/url-shortener#67]
Hey guys, 

We migrated to NestJS on our previous pr.
We need to change the installation paragraph at the readme.

**Comment by muskanbararia** [comment]
can u please assign it to me?

**Comment by muskanbararia** [comment]
Would love to work for it under hacktoberfest

**Comment by origranot** [comment]
> can u please assign it to me?

Sure!

**Comment by origranot** [comment]
@muskanbararia Any update?
