### ISSUE TITLE
Better Space utilization

### ISSUE THREAD

**Issue by manassahoo-dev** [origranot/url-shortener#74]
Currently, the items are placed at the top. So there is lot of negative space from top. 
We can make it center aligned to properly utilize the space.
![image](https://user-images.githubusercontent.com/6974223/194485846-4792b98e-6b6d-4c71-91ee-5bb0325245b2.png)

**Comment by manassahoo-dev** [comment]
@origranot Can you please assign this to me?

**Comment by manassahoo-dev** [comment]
This is how the updated version would look like
![image](https://user-images.githubusercontent.com/6974223/194494237-1cd388ad-85f9-468c-b9be-a823422ba276.png)

**Comment by origranot** [comment]
Nice idea. There is a PR opened by you.

**Comment by manassahoo-dev** [comment]
> Nice idea. There is a PR opened by you.

Yes, I have created the PR. Could you please review it once?

**Comment by origranot** [comment]
Sure.
