### ISSUE TITLE
Migrate to frontend framework

### ISSUE THREAD

**Issue by GuillemPM** [origranot/url-shortener#77]
As @origranot said, we should migrate to a frontend framework.
I could work on migrating to  [🔰**Vue.js**](https://vuejs.org)

I personally prefer Vue.js over React.js as it is so **powerful** framework and has a softer **learning curve** and its gaining more popularity over the time, if you prefer to migrate to React close this issue and let's wait for someone interested.

## Star History

[![Star History Chart](https://api.star-history.com/svg?repos=vuejs/vue,facebook/react,angular/angular&type=Date)](https://star-history.com/#vuejs/vue&facebook/react&angular/angular&Date)

**Comment by origranot** [comment]
@GuillemPM thank you so much for your contributions!

I want to use something better than O(N) frameworks.

How about qwick?

**Comment by GuillemPM** [comment]
Interesting, I will take a look :)

**Comment by GuillemPM** [comment]
@origranot I'll give it a try.
That's how I'm planning to structure the folders:
```js
root/
├─ dist/ //Will contain whole project solution to serve on HerokuApp or whatever.
├─ frontend/
│  ├─ dist/ //Will contain frontend solution which you can serve individually for development
│  ├─ node_modules/
│  ├─ qwik-files
│  ├─ package.json //Will contain scripts to build the frontend app
├─ backend/
│  ├─ dist/ //Will contain backend solution which you can serve individually for development
│  ├─ node_modules/
│  ├─ nest-files
│  ├─ package.json //Will contain scripts to build the backend app
url-shortener.code-worskpace //Will help developers to maintain an organized view of the project
package.json //Will contain scripts to build the whole project into a single app

```

**Comment by origranot** [comment]
I guess this is our only options.

You can go for it, looks great for me.

What do you think about qwick?

**Comment by GuillemPM** [comment]
The framework looks great, working under vite and its building and deploying really fast.
I don't have a lot of experience with React and since Qwik syntax is based on it, it is a little bit complex for me, but I almost have it ready.
Will update soon 🚀

**Comment by origranot** [comment]
@GuillemPM Sounds great!

**Comment by aigdonia** [comment]
I'm interested in this Qwik refactor thing, I saw the PR already creared, and I'm looking for the merge so I can add up over it

**Comment by origranot** [comment]
Hey, I think @GuillemPM is working on this issue already. 

You are welcome to contribute in other ways. Take a look into the docs.

**Comment by GuillemPM** [comment]
PR #127
