### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by aditi10701** [origranot/url-shortener#89]
add a footer to the section which makes the app a better visual impact.
kindly assign me the same. I am interested in working on this.

**Comment by origranot** [comment]
Hey @aditi10701 

I am more than happy that someone suggested that.
Go for it!

**Comment by amittri1025** [comment]
I Added a Footer in PR #90 , which gives link to original github repo. It was very crucial.

**Comment by origranot** [comment]
@amittri1025 I review the pr.

Please have a look.
