### ISSUE TITLE
I will create the Better readme

### ISSUE THREAD

**Issue by BxtGeek** [origranot/url-shortener#92]

**Comment by origranot** [comment]
Great!

You are welcome to open a PR.

**Comment by BxtGeek** [comment]
[README.md](https://github.com/origranot/url-shortener/files/9737893/README.md)

**Comment by BxtGeek** [comment]
Added the new readme file

**Comment by origranot** [comment]
Did you open a pr?

**Comment by BxtGeek** [comment]
Thanks will edit and update

**Comment by origranot** [comment]
@BxtGeek Any update? 

I want to create a cool readme :)
